name: Build & Train

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      working-directory: .\.\TitanicPredictions
      run: dotnet restore
    - name: Build
      working-directory: .\.\TitanicPredictions
      run: dotnet build --configuration Release --no-restore
    - name: Train
      working-directory: .\.\TitanicPredictions
      run: dotnet run --no-restore --verbosity normal
